# Generated by Django 4.0.3 on 2022-05-01 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(default='NA', max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('totalDue', models.DecimalField(decimal_places=3, default=0, max_digits=19)),
                ('lastPayment', models.DecimalField(decimal_places=3, default=0, max_digits=19)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('active_customer', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GASTransection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inDate', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=19)),
                ('totalSale', models.DecimalField(decimal_places=3, max_digits=19)),
                ('cashDeposited', models.DecimalField(decimal_places=3, max_digits=19)),
                ('perQubicLiter', models.DecimalField(decimal_places=3, max_digits=19)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OilStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryDate', models.DateField()),
                ('oilQuantity', models.DecimalField(decimal_places=3, max_digits=19)),
                ('oilType', models.CharField(max_length=10)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockLeft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('oilQuantity', models.DecimalField(decimal_places=3, max_digits=19)),
                ('oilType', models.CharField(max_length=10)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('oilLeft', models.DecimalField(decimal_places=3, max_digits=19, verbose_name='Oil in Stock')),
                ('totalOilSale', models.DecimalField(decimal_places=3, max_digits=19, verbose_name='Total Oil Sale')),
                ('price', models.DecimalField(decimal_places=3, max_digits=19, verbose_name='Price')),
                ('totalRevenue', models.DecimalField(decimal_places=3, max_digits=19, verbose_name='Total Sale(Taka)')),
                ('cashDeposited', models.DecimalField(decimal_places=3, max_digits=19, verbose_name='Total Cash')),
                ('overdue', models.DecimalField(decimal_places=3, max_digits=19, verbose_name='Total Due')),
                ('oilType', models.CharField(max_length=10, verbose_name='Oil Type')),
                ('comments', models.TextField(default='', verbose_name='Comments')),
                ('dipReading', models.DecimalField(decimal_places=3, default=0, max_digits=19, verbose_name='DIP Reading')),
                ('twoPercent', models.DecimalField(decimal_places=3, default=0, max_digits=19, verbose_name='Two Percent')),
                ('validTransection', models.BooleanField(default=True, verbose_name='Valid Transection')),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DebitToCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('oilQuantity', models.DecimalField(decimal_places=3, max_digits=19)),
                ('oilType', models.CharField(max_length=10)),
                ('TodayDue', models.DecimalField(decimal_places=3, default=0, max_digits=19)),
                ('totalAmountDue', models.DecimalField(decimal_places=3, default=0, max_digits=19)),
                ('totalAmountPaid', models.DecimalField(decimal_places=3, default=0, max_digits=19)),
                ('oilUnitPrice', models.DecimalField(decimal_places=3, default=0, max_digits=19)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='HishabNikash.customer')),
            ],
        ),
    ]
