# Generated by Django 4.0.4 on 2022-05-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HishabNikash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GASLastReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=19)),
            ],
        ),
    ]
